# Generated by Django 4.2 on 2025-12-30 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['qr_data'], name='events_tick_qr_data_fe2142_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['payment_status'], name='events_tick_payment_4e4a03_idx'),
        ),
    ]
